name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install system dependencies
      run: |
        sudo snap install radare2 --classic
        echo 'e scr.color=1' >> ~/.radare2rc
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt
    - name: Run pytest
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        comment_mode: off
        files: |
          junit/test-results.xml
    - name: Create Code Coverage summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        format: markdown
        output: file
    - name: Write code coverage to job summary
      run: |
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
