name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup radare2 wrapper script
      run: |
        echo "$PWD/.github/bin" >> $GITHUB_PATH
        export PATH="$PATH:"
        echo 'e scr.color=1' >> ~/.radare2rc
    - name: Echo path
      run: |
        echo $PATH
    - name: See env
      run: |
        env
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run pytest
      run: |
        pytest
